import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { getChallenge, getChallengeLeaderboard, startChallenge, submitChallenge } from "../../api/client";
import StudentLayout from "./StudentLayout";
import "./challenge.css";

const seconds = (value) => `${String(Math.max(0, Math.floor(value / 60))).padStart(2, "0")}:${String(Math.max(0, value % 60)).padStart(2, "0")}`;

export default function ChallengePlay() {
  const { id } = useParams(); const navigate = useNavigate();
  const [challenge, setChallenge] = useState(null), [step, setStep] = useState("intro"), [index, setIndex] = useState(0), [answers, setAnswers] = useState({}), [left, setLeft] = useState(0), [result, setResult] = useState(null), [board, setBoard] = useState([]), [error, setError] = useState("");
  useEffect(() => { getChallenge(id).then((c) => { setChallenge(c); setLeft(c.time_limit); if (c.completed) setStep("done"); }).catch(() => setError("This challenge is unavailable.")); }, [id]);
  useEffect(() => { if (step !== "game") return; if (left <= 0) { finish(); return; } const t = setInterval(() => setLeft((n) => n - 1), 1000); return () => clearInterval(t); }, [step, left]);
  const question = challenge?.questions?.[index]; const progress = useMemo(() => challenge?.questions?.length ? ((index + 1) / challenge.questions.length) * 100 : 0, [challenge, index]);
  const begin = async () => { try { await startChallenge(id); setStep("game"); } catch (e) { setError(e.data?.detail || "You have already completed this challenge."); } };
  const finish = async () => { if (step === "submitting" || !challenge) return; setStep("submitting"); try { const data = await submitChallenge(id, { answers }); setResult(data); setBoard(await getChallengeLeaderboard(id)); setStep("done"); } catch (e) { setError(e.data?.detail || "Could not submit your answers."); setStep("game"); } };
  const answer = (value) => setAnswers((old) => ({ ...old, [question.id]: value }));
  if (error) return <StudentLayout title="Boss Battle"><div className="s-error">{error}</div></StudentLayout>;
  if (!challenge) return <StudentLayout title="Boss Battle"><div className="s-loading">Loading challenge...</div></StudentLayout>;
  if (step === "intro") return <StudentLayout title="Mission Boss Battle"><section className="challenge-hero"><span>⚔️ BOSS BATTLE</span><h1>{challenge.title}</h1><p>{challenge.description}</p><div><b>+{challenge.xp_reward} XP</b><b>{Math.ceil(challenge.time_limit / 60)} min</b></div><button className="btn btn-primary" onClick={begin}>Start Challenge</button></section></StudentLayout>;
  if (step === "done") return <StudentLayout title="Challenge Complete"><section className="challenge-hero celebrate"><span>🎉 GREAT WORK!</span><h1>Boss battle complete</h1>{result && <div className="result-grid"><b>{result.score}<small>Score</small></b><b>{result.accuracy}%<small>Accuracy</small></b><b>+{result.xp_earned}<small>XP earned</small></b><b>{seconds(result.time_taken)}<small>Time</small></b></div>}<h2>Top players</h2><ol className="leaderboard">{board.map((row) => <li className={row.is_current_student ? "mine" : ""} key={row.id}><span>#{row.rank} {row.student_name}</span><span>{row.score} pts · {seconds(row.time_taken)}</span></li>)}</ol><button className="btn btn-primary" onClick={() => navigate("/challenges")}>Continue</button></section></StudentLayout>;
  const content = question.content || {};
  return <StudentLayout title="Boss Battle"><section className="game-card"><header><span>Question {index + 1} / {challenge.questions.length}</span><strong>⏱ {seconds(left)}</strong></header><div className="game-progress"><i style={{ width: `${progress}%` }} /></div><h2>{content.question || content.task || "Complete this activity"}</h2>{question.question_type === "multiple_choice" && <div className="option-grid">{(content.options || []).map((o, i) => <button className={answers[question.id] === i ? "selected" : ""} onClick={() => answer(i)} key={o}>{o}</button>)}</div>}{question.question_type === "true_false" && <div className="option-grid"><button className={answers[question.id] === true ? "selected" : ""} onClick={() => answer(true)}>True</button><button className={answers[question.id] === false ? "selected" : ""} onClick={() => answer(false)}>False</button></div>}{["fill_blank", "prompt_build"].includes(question.question_type) && <textarea value={answers[question.id] || ""} onChange={(e) => answer(e.target.value)} placeholder="Write your answer here..." rows={7} />}{question.question_type === "drag_order" && <p className="game-hint">Put the items in order, separated by commas.</p>}{["drag_order", "match_pairs"].includes(question.question_type) && <textarea value={answers[question.id] || ""} onChange={(e) => answer(e.target.value)} placeholder="Your arrangement or matches" rows={4} />}<footer><button className="btn btn-secondary" disabled={!index} onClick={() => setIndex(index - 1)}>Back</button><button className="btn btn-primary" onClick={() => index === challenge.questions.length - 1 ? finish() : setIndex(index + 1)}>{index === challenge.questions.length - 1 ? "Finish Battle" : "Next"}</button></footer></section></StudentLayout>;
}
