# Generated by Django 6.0.6 on 2026-07-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_gamified_challenges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengequestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='challenge',
            name='time_limit',
            field=models.PositiveIntegerField(default=600, help_text='Time allowed in seconds'),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Seconds'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='camp.assignment'),
        ),
    ]
