# Generated by Django 6.0.6 on 2026-07-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_alter_challengequestion_question_type'),
        ('users', '0004_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal')], max_length=32)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp.challengequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_completions', to='users.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'puzzle_type'), name='unique_student_puzzle_type')],
            },
        ),
    ]
