# Generated by Django 6.0.6 on 2026-07-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_campsettings_remove_challenge_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='lesson',
        ),
    ]
