# Generated by Django 6.0.6 on 2026-07-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_remove_challenge_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlecompletion',
            name='assignment_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp.assignmentquestion'),
        ),
    ]
