# Generated by Django 6.0.6 on 2026-07-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_puzzlecompletion_assignment_question'),
        ('users', '0004_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('time_taken', models.PositiveIntegerField(help_text='Seconds, snapshot at finalization')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='win', to='camp.challenge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_wins', to='users.student')),
            ],
        ),
    ]
