# Generated by Django 6.0.6 on 2026-07-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_challengewin'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Classic (question list)'), ('dungeon_crawler', 'Dungeon Crawler'), ('target_shooter', 'Target Shooter'), ('escape_room', 'Escape Room'), ('floor_is_lava', 'Floor Is Lava'), ('ai_defense', 'AI Defense')], default='classic', max_length=32),
        ),
        migrations.AddField(
            model_name='challenge',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Classic (question list)'), ('dungeon_crawler', 'Dungeon Crawler'), ('target_shooter', 'Target Shooter'), ('escape_room', 'Escape Room'), ('floor_is_lava', 'Floor Is Lava'), ('ai_defense', 'AI Defense')], default='classic', max_length=32),
        ),
    ]
