# Generated by Django 6.0.6 on 2026-07-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_assignment_game_type_challenge_game_type'),
        ('users', '0004_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_logs', to='users.student')),
            ],
        ),
    ]
