# Generated by Django 6.0.6 on 2026-07-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_coinlog'),
        ('users', '0005_student_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('avatar', 'Avatar'), ('theme', 'Theme'), ('victory_effect', 'Victory Effect')], max_length=20)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='StudentCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='camp.cosmeticitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cosmetics', to='users.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'item'), name='unique_owned_cosmetic')],
            },
        ),
    ]
