# Generated by Django 6.0.6 on 2026-08-02 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
