# Generated by Django 6.0.6 on 2026-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0014_lesson_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='key_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
