# Generated by Django 6.0.6 on 2026-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0015_lesson_key_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding')], max_length=32),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding')], max_length=32),
        ),
        migrations.AlterField(
            model_name='puzzlecompletion',
            name='puzzle_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding')], max_length=32),
        ),
    ]
