# Generated by Django 6.0.6 on 2026-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0016_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge')], max_length=32),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge')], max_length=32),
        ),
        migrations.AlterField(
            model_name='puzzlecompletion',
            name='puzzle_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge')], max_length=32),
        ),
    ]
