# Generated by Django 6.0.6 on 2026-08-26 08:10

import camp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0017_alter_assignmentquestion_question_type_and_more'),
        ('users', '0006_student_equipped_avatar_student_equipped_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge'), ('project_submission', 'Project Submission')], max_length=32),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge'), ('project_submission', 'Project Submission')], max_length=32),
        ),
        migrations.AlterField(
            model_name='puzzlecompletion',
            name='puzzle_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge'), ('project_submission', 'Project Submission')], max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_url', models.URLField(blank=True)),
                ('submitted_zip', models.FileField(blank=True, null=True, upload_to=camp.models.project_submission_zip_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('results', models.JSONField(default=list)),
                ('score_fraction', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='camp.assignmentquestion')),
                ('challenge_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='camp.challengequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('assignment_question__isnull', True), ('challenge_question__isnull', False)), models.Q(('assignment_question__isnull', False), ('challenge_question__isnull', True)), _connector='OR'), name='project_submission_exactly_one_question')],
            },
        ),
    ]
