# Generated by Django 6.0.6 on 2026-08-31 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0018_alter_assignmentquestion_question_type_and_more'),
        ('users', '0006_student_equipped_avatar_student_equipped_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='qa_enabled',
            field=models.BooleanField(default=False, help_text='If on, students see a Q&A box for this lesson on the Week 6 hub.'),
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('hidden', 'Hidden')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to='camp.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
