# Generated by Django 6.0.6 on 2026-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0020_lost_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiongameprogress',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missiongameprogress',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mazeobject',
            name='position',
            field=models.JSONField(default=list, help_text='[x, y] grid position'),
        ),
        migrations.AlterField(
            model_name='mazeobject',
            name='reward_data',
            field=models.JSONField(blank=True, default=dict, help_text='XP, coins, item and effect configuration'),
        ),
    ]
