# Generated by Django 6.0.6 on 2026-09-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0021_missiongameprogress_coins_missiongameprogress_xp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missiongameprogress',
            old_name='completed_objects',
            new_name='answered_questions',
        ),
        migrations.RenameField(
            model_name='missiongameprogress',
            old_name='inventory',
            new_name='completed_rounds',
        ),
        migrations.RemoveField(
            model_name='missiongameprogress',
            name='health',
        ),
        migrations.RemoveField(
            model_name='missiongameprogress',
            name='position',
        ),
        migrations.AddField(
            model_name='missiongameprogress',
            name='answered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missiongameprogress',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LostGridRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='⚡', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('coin_reward', models.PositiveIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lostgrid_rounds', to='camp.mission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LostGridQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('drag_order', 'Drag order'), ('match_pairs', 'Match pairs'), ('fill_blank', 'Fill in the blank'), ('prompt_build', 'Prompt build'), ('memory_tiles', 'Memory Tiles'), ('word_search', 'Word Search'), ('image_reveal', 'Image Reveal'), ('interactive_coding', 'Interactive Coding'), ('coding_challenge', 'Coding Challenge'), ('project_submission', 'Project Submission')], max_length=32)),
                ('points', models.PositiveIntegerField(default=10)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_question', models.ForeignKey(blank=True, help_text='Pulls live content from the question bank instead of the inline fields below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lostgrid_questions', to='camp.challengequestion')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='camp.lostgridround')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
