# Generated by Django 6.0.6 on 2026-09-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0022_rename_completed_objects_missiongameprogress_answered_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostgridquestion',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Seconds allowed to answer before it's auto-skipped as timed out. Blank = no limit.", null=True),
        ),
    ]
