# Generated by Django 6.0.6 on 2026-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0023_lostgridquestion_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiongameprogress',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missiongameprogress',
            name='had_miss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythical', 'Mythical')], max_length=50),
        ),
    ]
