# Generated by Django 6.0.6 on 2026-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0024_missiongameprogress_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsettings',
            name='is_graduation',
            field=models.BooleanField(default=False),
        ),
    ]
