# Generated by Django 6.0.6 on 2026-09-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0025_campsettings_is_graduation'),
        ('users', '0006_student_equipped_avatar_student_equipped_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('builder', '🏆 Builder Award'), ('problem_solver', '🧠 Problem Solver'), ('ai_explorer', '🤖 AI Explorer'), ('future_innovator', '🚀 Future Innovator'), ('creative_mind', '🎨 Creative Mind'), ('fast_learner', '⚡ Fast Learner'), ('never_give_up', '💪 Never Give Up'), ('rising_developer', '🌟 Rising Developer'), ('quest_master', '🎯 Quest Master'), ('tech_trailblazer', '💻 Tech Trailblazer')], max_length=32)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.student')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'award_type'), name='unique_student_award_type')],
            },
        ),
    ]
