# Generated by Django 6.0.6 on 2026-07-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0012_cosmeticitem_studentcosmetic'),
        ('users', '0005_student_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='equipped_avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'avatar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='camp.cosmeticitem'),
        ),
        migrations.AddField(
            model_name='student',
            name='equipped_theme',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'theme'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='camp.cosmeticitem'),
        ),
        migrations.AddField(
            model_name='student',
            name='equipped_victory_effect',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'victory_effect'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='camp.cosmeticitem'),
        ),
    ]
